# -*- mode: ruby -*-
# vi: set ft=ruby :

# Required workaround to have different users for provisioning and SSH access.
VAGRANT_COMMAND = ARGV[0]

# Username to be used in box.
BOX_USERNAME = "titze"
BOX_NAME = "CTFbox"

Vagrant.configure("2") do |config|
  # Configure the box.
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "ctfbox"

  # Configure SSH access.
  config.ssh.forward_x11 = true # Required for shared clipboard.
  if VAGRANT_COMMAND == "ssh"
    config.ssh.username = BOX_USERNAME
  end

  # Increase RAM and CPUs.
  config.vm.provider "virtualbox" do |vb|
    vb.name = BOX_NAME
    vb.memory = "4096"
    vb.cpus = "2"
  end

  # Share host folder.
  #config.vm.synced_folder "~/Desktop/ctf", "/ctf"

  # Provisioning: Install required dev tools.
  config.vm.provision "shell", path: "../scripts/ubuntu/upgrade.sh"

  config.vm.provision "shell", path: "../scripts/ubuntu/dev-essentials.sh"
  config.vm.provision "shell", path: "../scripts/ubuntu/multiarch.sh"
  config.vm.provision "shell", path: "../scripts/ubuntu/sec-essentials.sh"
  config.vm.provision "shell", path: "../scripts/ubuntu/python.sh"
  config.vm.provision "shell", path: "../scripts/ubuntu/pwntools.sh"
  config.vm.provision "shell", path: "../scripts/ubuntu/ROPgadget.sh"
  config.vm.provision "shell", path: "../scripts/ubuntu/nvim.sh"
  config.vm.provision "shell", path: "../scripts/ubuntu/zsh.sh"
  config.vm.provision "shell", path: "../scripts/ubuntu/disable-aslr.sh"

  config.vm.provision "shell", path: "../scripts/packages/checksec.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/packages/peda.sh", privileged: false

  config.vm.provision "shell", path: "../scripts/dotfiles/nvim.sh", privileged: false
  config.vm.provision "shell", path: "../scripts/dotfiles/zsh.sh", privileged: false

  # Provisioning: Add user and configure SSH keys and sudo-privileges.
  config.vm.provision "shell", path: "../scripts/vagrant/cp-create-user.sh", args: "-u #{BOX_USERNAME} -s /usr/bin/zsh -g vagrant"
end
